### ISSUE TITLE
Please update release to reflect dependency changes

### ISSUE THREAD

**Issue by boedy** [bendrucker/snakecase-keys#11]
We use both your package as the related `camelcase-keys` package. Currently the behaviour between both packages is inconsistent when converting an array of objects.

**Example code:**
```
console.log(snakeCaseKeys([{fooBar: 'test'}]));
```

**Expected**
```
[ { foo_bar: 'test' } ]
```

**Accutual**
```
{ '0': { foo_bar: 'test' } }
```

The current master branch is consistent with `camelcase-keys`.

Is there something holding you back from releasing this?

**Comment by boedy** [comment]
Wow, That was fast! Thanks 👏

**Comment by bendrucker** [comment]
Test was sitting on my laptop uncommitted!
