### ISSUE TITLE
snakecase-keys is destroying the Buffer

### ISSUE THREAD

**Issue by paradox37** [bendrucker/snakecase-keys#118]
Hello,

It seems that snakecase-keys is destroying the Buffer during the conversion. Take this example:

```
const file = {
  name: 'file.pdf',
  mimeType: 'application/pdf',
  buffer: Buffer.from('invoice content'),
};
```

Console log before using snakecase-keys will provide this:

`buffer: <Buffer 69 6e 76 6f 69 63 65 20 63 6f 6e 74 65 6e 74>`

After using snakecase-keys, I get this:
```
buffer: {
    '0': 105,
    '1': 110,
    '2': 118,
    '3': 111,
    '4': 105,
    '5': 99,
    '6': 101,
    '7': 32,
    '8': 99,
    '9': 111,
    '10': 110,
    '11': 116,
    '12': 101,
    '13': 110,
    '14': 116
  }
```

If I put `deep` to `false`, issue is not present, so somewhere there is an issue.

**Comment by bendrucker** [comment]
Duplicates https://github.com/bendrucker/snakecase-keys/issues/71

PR welcome to add an option that would allow users to skip based on the value in addition to the key:

https://github.com/bendrucker/snakecase-keys/issues/71#issuecomment-1121636032
