### ISSUE TITLE
Problem with dependencie map-obj

### ISSUE THREAD

**Issue by Neira1991** [bendrucker/snakecase-keys#14]
Hello, I added this code in webpack so that it transpires the code of your dependency because it has an arrow function then i have problems with IE :)
`{
         test: /\.jsx?$/,
         include: [/node_modules\/(snakecase-keys\/).*/],
         loader: ['babel-loader', 'ts-loader'],
       },`

**Comment by bendrucker** [comment]
Hi, please transpile dependencies appropriately for your browser targets. I'm not interested in supporting engines that don't support ES6 and declare as much:

https://github.com/bendrucker/snakecase-keys/blob/master/package.json#L35
