### ISSUE TITLE
Objects inside of arrays are not snake cased

### ISSUE THREAD

**Issue by scottbedard** [bendrucker/snakecase-keys#2]
I'm not sure if this is a bug, or intended behavior. If this is not a bug, my apologies, go ahead and just close this issue.

Anyway, it doesn't appear that objects inside of arrays are snake cased. When I submit the following...

```js
snakeCaseKeys({ fooBar: [{ bazQux: null }] });
```

I would expect to receive this...

```js
{ foo_bar: [{ baz_qux: null }] }
```

But instead I get this...

```js
{ foo_bar: [{ bazQux: null }] }
```

**Comment by bendrucker** [comment]
Unclear I guess. The readme definitely mentions objects. You’re welcome to submit a PR updating the code, tests, and docs for arrays and I’ll reciew it. I’ll keep the current behavior for now.
