### ISSUE TITLE
Incorrect conversion of some keys

### ISSUE THREAD

**Issue by juanpaco** [bendrucker/snakecase-keys#4]
I'm not sure where in the chain this breaks down, but when I get the following problem:

```
> snakeCaseKeys({ s1Bent: 1 })
{ s1bent: 1 }
```

I expect `{ s1_bent: 1 }`

It does work as expected for:

```
> snakeCaseKeys({s3FacePits: 1})
{ s3_face_pits: 1 }
```

There are some keys it converts incorrectly.

**Comment by juanpaco** [comment]
On closer inspection, it's the keys that only have 1 word after the number that are having problems.

So `s1Bent` and `s2Thing` fail, but `s1TwoWords` would turn out correctly.

**Comment by bendrucker** [comment]
This package uses https://github.com/ianstormtaylor/to-snake-case

I can see the argument that numbers should be considered separators. I'll leave you to research other packages on npm, see how they handle numbers, and send a PR for an equivalent (in size) replacement if you'd like to see this changed.

**Comment by juanpaco** [comment]
Fair enough.  It's inconsistent in either case.  The number gets treated as a separator if there are 2 or more words after it, but not if there is only 1.

I'll take the issue there though.

**Comment by bendrucker** [comment]
Yup, makes sense. Feel free to just replace the library if you find a suitable alternative instead of filing a PR with to-snake-case. Either is fine with me. I did pick to-snake-case because it's small when bundled for the browser though, just make sure to find something that's similar.
