### ISSUE TITLE
Compatability with FormData

### ISSUE THREAD

**Issue by putskan** [bendrucker/snakecase-keys#43]
Hi!
I've tried using it to change all axios requests to the server, however, it currently does not seem to support FormData objects.
I'd suggest supporting it or at least not dropping it :)

https://stackoverflow.com/posts/66883512/edit

**Comment by bendrucker** [comment]
Closing for lack of detail. SO link doesn't work. This doesn't sound like a bug but without a clear repro it's impossible to tell.
