### ISSUE TITLE
Handle passed arrays more graceful

### ISSUE THREAD

**Issue by valkum** [bendrucker/snakecase-keys#64]
According to https://github.com/sindresorhus/map-obj/issues/39 map-obj is not expected to handle arrays but currently does (in version 4.x). 

Currently these are allowed per the typescript definition in snakecase-keys and simply work (see See https://codesandbox.io/s/focused-carson-dmqpix?file=/src/index.ts). Using map-obj 5.0.x will break this.

To not break current behavior in snakecase-keys, and to be more compatible with camelcase-keys:
snakecase-keys should check if the passed obj is an array, and in that case call map-obj on each element instead of passing the obj to map-obj.

**Comment by bendrucker** [comment]
Updating to map-obj@5 would be a breaking change here, as it requires conversion to an ESM module. If at some point I do go ahead with that, I'd just include the array behavior changes as another breaking change.
