### ISSUE TITLE
Unable to convert the snakeCase keys response object into a FormData for file upload

### ISSUE THREAD

**Issue by eliezerp3** [bendrucker/snakecase-keys#71]
Hi. I'm am having a weird bug trying to upload a file when used in conjunction with this package. I have a function like below to convert a payload object into FormData for file upload.
```
const convertToFormData = ({ ...payload }) => {
  const formData = new FormData();
  Object.keys(payload).forEach((key) => {
    formData.append(key, payload[key]);
  });
  return formData;
};
```

When uploading a payload (a simple object containing title, body, and a image which is a file from a file input field) as below works fine:
```
convertToFormData(payload)
```
Payload From Chrome Dev Tools:
![Screen Shot 2022-05-09 at 2 44 49 PM](https://user-images.githubusercontent.com/30153503/167476530-5e96d1ad-b2a6-42a0-9f6d-52f705355851.png)

Now, when i try to do the same thing, only first converting the keys using snakecaseKeys, I get that the image is not in the correct format.
```
convertToFormData(snakecaseKeys(payload))
```
Payload From Chrome Dev Tools:
![Screen Shot 2022-05-09 at 2 48 28 PM](https://user-images.githubusercontent.com/30153503/167477085-a0f4a305-2b91-4093-b44c-3c5b5905b98b.png)

As you can see, without snakecaseKeys, it correctly converts the image to binary but for some reason adding in snakecaseKeys before converting to formData uploads the image as an object instead which fails.

Would appreciate the help. Thank you!

**EDIT**

Upon further debugging:
```
console.log(payload)
```
returns
```
{ title: 'asdas', body: 'ads', image: File }
```
But
```
console.log(snakecaseKeys(payload))
```
returns
```
{title: 'asdas', body: 'ads', image: {…} }
```

Any idea as to why it is converting the image File type to a regular object?

**Comment by bendrucker** [comment]
A `File` is itself an object and gets recursively snake cased by default. Use `{deep: false}` or set `exclude` to prevent this.

**Comment by eliezerp3** [comment]
I see but let’s say I would have keys that I do want to be recursively snake cased. Shouldn’t there be a check to not perform snake casing on special built in types like File.. and only perform it on regular custom objects?

**Comment by bendrucker** [comment]
That's a feature request, you could take a stab at an API and implementation for that if you'd like.

**Comment by eliezerp3** [comment]
I hear. Thank you. Just by the way; setting deep to false worked fine but setting exclude to [“image”] didn’t work. Could it be that only the parent key “image” gets excluded but not its nested keys?

**Comment by bendrucker** [comment]
Yes, on second thought `exclude` only prevents key transformation, not recursion.

**Comment by bendrucker** [comment]
I would take a PR adding a `shouldRecurse` that is a `(key, value) => Boolean`:

https://github.com/sindresorhus/map-obj#shouldrecurse

That would allow you to add logic skipping recursion on values of specified types or on certain keys.
