### ISSUE TITLE
Keys convertation breaks file instance

### ISSUE THREAD

**Issue by J4CKVVH173** [bendrucker/snakecase-keys#74]
I have an object with file object inside of this object. When I put this object in snakecaseKeys function the result has broken object.

![image_2022-06-16_18-13-38](https://user-images.githubusercontent.com/33596000/174106260-5bde83ba-b9fa-43bf-9a2b-cf9fd0b9cc95.png)
The first line is input and the second is output.

Maybe you should to exclude native objects like File, Blob and etc from snakecase transformation ?

**Comment by bendrucker** [comment]
Duplicates https://github.com/bendrucker/snakecase-keys/issues/71

**Comment by J4CKVVH173** [comment]
I checked your [map-obj](https://github.com/bendrucker/map-obj). I saw that you have a value validation is it object or not ([validation](https://github.com/bendrucker/map-obj/blob/5378effeb64bafa7aa39301fec4a8211e6b2d9ad/index.js#3)  and [isObject](https://github.com/bendrucker/map-obj/blob/5378effeb64bafa7aa39301fec4a8211e6b2d9ad/index.js#L4)). Why you didn't add File, Blob and etc special types in this validation ? They are not a regular objects like class instance or base object in js.
